version: 2.1
orbs:
  node: circleci/node@4.1

jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '14'
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - run: npm test

workflows:
  build-deploy:
    jobs:
      - build-and-test
