version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:16.3.0-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm test
  deploy:
    # 배포 작업 설정...

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              only: main
  deploy:
    jobs:
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: release
